### ISSUE TITLE
smtp authentication

### ISSUE THREAD

**Issue by alexstaj** [maxplanck-ie/bcl2fastq_pipeline#6]
hi

I love your work. would you please let me know how to use it with smtp authentication so my gmail account can send the messages.  thank you for your hard work!

**Comment by dpryan79** [comment]
You'd need to modify the email functions in `misc.py` as mentioned [here](https://stackoverflow.com/questions/10147455/how-to-send-an-email-with-gmail-as-provider-using-python) I presume.
