### ISSUE TITLE
Use R2 instead of R1 with fastq_screen for scRNA-seq data 

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/bcl2fastq_pipeline#8]
For both CelSeq2 and 10X, R2 contains the informative cDNA sequence, while R1 carries the CB, UMI, and polyA/T-stretch.
Using R1 for contamination screen is uninformative.
Can you switch to R2 for these two protocols instead?

**Comment by dpryan79** [comment]
The demultiplexing pipeline isn't aware of the experiment type, but I think it would make sense to modify it to use read 2 if present anyway for exactly the reasons you listed.

**Comment by katsikora** [comment]
I see. Yes, perhaps using read 2 for all paired-end projects would be a good idea.
